In [2]:
%store -r extended_history
#note must be running in same python env/kernel session

extended_history

,song_name,artist_name,album_name,play_count,total_ms_played,skip_count
0,warning,midwxst,warning,32,1868286,18
1,Lonely,Imagine Dragons,Mercury - Acts 1 & 2,213,14229530,128
2,I'll Do It - Sped Up,Six Dior,I'll Do It,36,596126,30
3,"Tokyo Drift (Fast & Furious) - From ""The Fast ...",Teriyaki Boyz,The Fast And The Furious: Tokyo Drift,128,11072465,73
4,Consume (feat. Goon Des Garcons),Chase Atlantic,Chase Atlantic,20,1159677,16
...,...,...,...,...,...,...
13519,Go Boy,ODIE,Go Boy,1,12100,1
13520,Any Way You Want Me,BROCKHAMPTON,The Family,1,75275,0
13521,BOY BYE,BROCKHAMPTON,GINGER,1,142186,0
13522,SUMMER,BROCKHAMPTON,SATURATION II,2,134313,1
13523,NO HALO,BROCKHAMPTON,GINGER,1,9670,1